### ISSUE TITLE
Adding more accounts to testrpc-py

### ISSUE THREAD

**Issue by fredrbl** [pipermerriam/eth-testrpc#103]
* OS: Linux Lubuntu 16.04

I am using testrpc-py for research purposes, and in that regard it would be perfect to add more accounts. In the js testrpc this is simply done by initialise testrpc --accounts "number"
However, I have not found a simple manner of increasing the amount for testrpc-py. Is there a command for this, or could I implement it another way?

![image](https://user-images.githubusercontent.com/24275263/32404890-bc9e6318-c138-11e7-8e37-cd2464036a3e.png)

**Comment by pipermerriam** [comment]
Do you need the RPC functionality or are you able to interact with the tester directly from python?

If it's the latter, I'd suggest taking a look at [`eth-tester`](https://github.com/ethereum/eth-tester)

Otherwise you'll need to wait a bit or submit a pull request with this functionality yourself.  This library is no longer being maintained as it's being replaced by the `eth-tester` library linked above.

**Comment by fredrbl** [comment]
aaaah perfect Piper, eth-tester covers my needs:) Thanks!
